version: '3.9'

services:
  web:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_db
    ports:
      - '5432:5432'
